In [1]:
import numpy as np


In [2]:
array_one=np.array([1,2,3,4,5,6])

In [3]:
array_one

array([1, 2, 3, 4, 5, 6])

In [4]:
num=[11,22,33,44,55,66,77]

In [5]:
array_two=np.array(num)

In [6]:
array_two

array([11, 22, 33, 44, 55, 66, 77])

In [20]:
array_of_ones=np.ones((3,2),dtype=int)

In [21]:
array_of_ones

array([[1, 1],
       [1, 1],
       [1, 1]])

In [17]:
array_of_zeros=np.zeros((2,3))

In [16]:
array_of_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

All created are type float

In [13]:
array_empty=np.empty((3,2))

In [14]:
array_empty

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
array_eye=np.eye(4)
#creates a square 

In [23]:
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
array_of_evens=np.arange(2,26,2)
#start,end,interval

In [27]:
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [28]:
array_2D=np.array([(3,1,5),(6,1,4)])

In [29]:
array_2D

array([[3, 1, 5],
       [6, 1, 4]])

In [30]:
array_2D.shape

(2, 3)

In [38]:
array_of_evens.reshape(2,6)

array([[ 2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24]])

In [39]:
print(array_of_evens)


[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [2]:
#Universal Functions
import numpy as np

circle_radii=np.array([7,14,21])

In [5]:
circle_diameter=circle_radii*2

circle_diameter

In [6]:
print(circle_diameter)

[14 28 42]


In [7]:
circle_area=np.pi* circle_radii**2

In [8]:
circle_area

array([ 153.93804003,  615.7521601 , 1385.44236023])

In [9]:
angle_degrees=np.array([30,60,90,180,270,360])

In [10]:
angle_radians=(np.pi/180) * angle_degrees

In [11]:
angle_radians

array([0.52359878, 1.04719755, 1.57079633, 3.14159265, 4.71238898,
       6.28318531])

In [15]:
print('Sine-Values:')

np.sin(angle_radians)

Sine-Values:


array([ 5.00000000e-01,  8.66025404e-01,  1.00000000e+00,  1.22464680e-16,
       -1.00000000e+00, -2.44929360e-16])

Flatten.np.flatten,np.nedier

ravel

In [17]:
x=np.array([[1,2] , [3,4]])
y=np.array([ [5,6],[7,8]])
z=(x*y)
z

array([[ 5, 12],
       [21, 32]])

In [18]:
x=np.array([4,6,2,8])
np.median(x)

5.0