## Broadcasting
Broadcasting allows arithmetic operations between arrays of differing shapes by effectively replicating the smaller array along the last mismatched dimension.

In [1]:
import numpy as np

#### Element-by-element operations
NumPy typicall performs element-by-element operations on two arrays of similar shapes

In [2]:
x = np.array([2, 4, 6, 8, 10])
y = np.array([5, 5, 5, 5, 5])

In [3]:
x * y

array([10, 20, 30, 40, 50])

#### Operations between arrays and scalars
When a scalar is used in an operation with an array x, then that scalar is effectively converted to an array matching the shape of the array x. The scalar is effectively broadcast to the entire array.

In [4]:
z = 10

In [5]:
x * z

array([ 20,  40,  60,  80, 100])

In [6]:
ones = np.ones((3,4))

In [7]:
ones * z

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

#### Create lists for information about some cars
We store data about the top speed and weights of 6 vehicles. The units for these values are km/h and kg.

In [8]:
top_speeds = [184, 243, 192, 309, 257, 218]
weights = [1178, 1243, 1403, 1047, 1673, 1475]

In [9]:
car_info = np.array([top_speeds, weights])

car_info

array([[ 184,  243,  192,  309,  257,  218],
       [1178, 1243, 1403, 1047, 1673, 1475]])

#### Create an containing values to convert the car_info array to Imperial units
These factors will be used to convert the car data to mph and lbs.

In [10]:
conversion_factors = np.array([0.621371, 2.20462])

conversion_factors

array([0.621371, 2.20462 ])

In [11]:
conversion_factors.shape

(2,)

In [12]:
car_info.shape

(2, 6)

### Broadcasting Rules
While performing operations on two arrays, NumPy compares their shapes element-wise. The dimensions are considered in reverse order, starting with the trailing dimensions, and working its way forward. Two dimensions are compatible when

* they are equal, <br />
* one of them is of size 1

##### The car_info and conversion_factors arrays are not compatible
The multiplication fails because there is a mismatch in the trailing dimensions <br />
car_info:  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2 x <b>6</b> <br />
conversion_factors: <b>2</b>

The trailing dimensions here are 6 and 2, so there is a mismatch

In [13]:
car_info * conversion_factors

ValueError: operands could not be broadcast together with shapes (2,6) (2,) 

#### Creating a new factors array with a different shape

In [14]:
new_factors = conversion_factors.reshape(2,1)

new_factors

array([[0.621371],
       [2.20462 ]])

In [15]:
new_factors.shape

(2, 1)

#### The multiplications succeeds this time

car_info:  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <b>2 x 6</b> <br />
new_factors: <b>2 x 1</b>

In [16]:
car_info * new_factors

array([[ 114.332264,  150.993153,  119.303232,  192.003639,  159.692347,
         135.458878],
       [2597.04236 , 2740.34266 , 3093.08186 , 2308.23714 , 3688.32926 ,
        3251.8145  ]])