## Fancy Indexing
NumPy arrays can be indexed with slices and also with boolean or integer arrays called <i>masks</i>. It means passing an array of indices to access multiple array elements at once. This method is called fancy indexing

In [1]:
import numpy as np
import csv

#### Create an array 
These are the squares of 0-13.

In [2]:
x = np.arange(14)**2

x

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169])

#### View the contents at specific indexes

In [3]:
x[3], x[7], x[9], x[13]

(9, 49, 81, 169)

#### Create a mask
This mask is a list of index locations (the same as what we used above)

In [4]:
mask_1 = [3, 7, 9, 13]

#### Use this mask on the NDArray
This prints out the elements present in the locations listed in the mask

In [5]:
x[mask_1]

array([  9,  49,  81, 169])

#### A mask can also be two dimensional

In [6]:
mask_2 = np.array([[3,5], [2,8]])

mask_2

array([[3, 5],
       [2, 8]])

#### Apply the 2D mask on the 1D array
The result is in the same shape as the mask (not the original array), and contains the elements corresponding to the index values passed in the mask

In [7]:
x[mask_2]

array([[ 9, 25],
       [ 4, 64]])

#### Create a 2D array to work with

In [8]:
cities = np.array([['Sydney', 'Auckland', 'Vancouver'],
                  ['Lima', 'Bogota', 'Lisbon'],
                  ['Istanbul', 'Tehran', 'Colombo']])

#### Define two arrays representing the corners of the cities array
The row coordinates are in the row array while the col array contains the column coordinates

In [9]:
row = np.array([[0,0], [2,2]])
col = np.array([[0,2], [0,0]])

In [10]:
cities[row, col]

array([['Sydney', 'Vancouver'],
       ['Istanbul', 'Istanbul']], dtype='<U9')

#### Accessing individual elements still works as expected

In [11]:
cities[1, 2]

'Lisbon'

#### Modify the array using a mask
Just like one can set the value of an element by referencing it using it's index locations, we can set values using the mask

In [12]:
cities[row, col] = 'aaaa'

cities

array([['aaaa', 'Auckland', 'aaaa'],
       ['Lima', 'Bogota', 'Lisbon'],
       ['aaaa', 'Tehran', 'Colombo']], dtype='<U9')

#### Modifying the 1D array with a mask

In [13]:
mask_1

[3, 7, 9, 13]

In [14]:
x[mask_1] = 999

x

array([  0,   1,   4, 999,  16,  25,  36, 999,  64, 999, 100, 121, 144,
       999])