## Fancy Indexing with Boolean Arrays
We can perform fancy indexing using boolean masks:
* These masks have the same shape as the array which is the target of the indexing
* They contain True/False values at the locations whose elements need to be included in the result
* The result is a 1D list of all elements in the target array at the locations which correspond to True values in the mask
* Often used to select elements in an array which satisfy a condition

In [1]:
import numpy as np

In [2]:
x = np.arange(12).reshape(3, 4)

In [3]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Create a mask 
This is the same shape as x, and contains True values in any location where the x contains an element matching the given condition

In [4]:
index_bool = x > 6

In [5]:
index_bool

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

#### Apply the mask to the target array
This returns a 1D array containing all elements matching the given condition

In [6]:
x[index_bool]

array([ 7,  8,  9, 10, 11])

#### The result is identical to applying a condition directly on the array

In [7]:
print(x[x > 6])

[ 7  8  9 10 11]


### Counting operations

In [8]:
x < 7

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False]])

#### The count_nonzero() function
For a boolean array, this effectively counts the number of True elements

In [9]:
np.count_nonzero(x < 7)

7

#### Each True occurrence has a value of 1

In [10]:
np.sum(x < 7)

7

#### Count the number of True values in each row

In [11]:
np.sum(x < 7, axis = 1)

array([4, 3, 0])

#### The any() function
Is there any element in the array which matches this condition?

In [12]:
np.any(x > 8)

True

#### The all() operation
Do all elements in the array satisfy the given condition?

In [13]:
np.all(x < 11)

False

In [14]:
np.all(x < 50)

True

#### Apply the all() function to each row

In [15]:
np.all(x < 10 , axis = 1)

array([ True,  True, False])